const usStates = [
  { name: "Kentucky", fee: 40 },
  { name: "Arkansas", fee: 45 },
  { name: "Arizona", fee: 50 },
  { name: "Colorado", fee: 50 },
  { name: "Hawaii", fee: 50 },
  { name: "Iowa", fee: 50 },
  { name: "Michigan", fee: 50 },
  { name: "Mississippi", fee: 50 },
  { name: "Missouri", fee: 50 },
  { name: "New Mexico", fee: 50 },
  { name: "Utah", fee: 54 },
  { name: "California", fee: 70 },
  { name: "Montana", fee: 70 },
  { name: "Ohio", fee: 99 },
  { name: "Georgia", fee: 100 },
  { name: "Idaho", fee: 100 },
  { name: "Indiana", fee: 100 },
  { name: "Louisiana", fee: 100 },
  { name: "Maryland", fee: 100 },
  { name: "Nebraska", fee: 100 },
  { name: "New Hampshire", fee: 100 },
  { name: "Oklahoma", fee: 100 },
  { name: "Oregon", fee: 100 },
  { name: "Virginia", fee: 100 },
  { name: "West Virginia", fee: 100 },
  { name: "Wyoming", fee: 100 },
  { name: "Connecticut", fee: 120 },
  { name: "Florida", fee: 125 },
  { name: "New Jersey", fee: 125 },
  { name: "North Carolina", fee: 125 },
  { name: "Pennsylvania", fee: 125 },
  { name: "Vermont", fee: 125 },
  { name: "Wisconsin", fee: 130 },
  { name: "North Dakota", fee: 135 },
  { name: "Illinois", fee: 150 },
  { name: "Rhode Island", fee: 150 },
  { name: "South Dakota", fee: 150 },
  { name: "Minnesota", fee: 155 },
  { name: "Kansas", fee: 160 },
  { name: "Maine", fee: 175 },
  { name: "Alabama", fee: 200 },
  { name: "New York", fee: 200 },
  { name: "Washington", fee: 200 },
  { name: "Alaska", fee: 250 },
  { name: "Tennessee", fee: 300 },
  { name: "Texas", fee: 300 },
  { name: "Nevada", fee: 425 },
  { name: "Massachusetts", fee: 500 }
];

const packages = [
  { name: "Starter", price: 299, description: "Basic LLC formation" },
  { name: "Growth", price: 499, description: "LLC + EIN + Banking setup" },
  { name: "Scale", price: 799, description: "Full package + ITIN + Tax filing" }
];

const addons = [
  { name: "Expedited Filing", price: 50 },
  { name: "Operating Agreement", price: 100 },
  { name: "Registered Agent (1 year)", price: 100 },
  { name: "EIN Application", price: 50 },
  { name: "ITIN Application", price: 150 },
  { name: "US Bank Account Setup", price: 100 }
];
